<a href="https://colab.research.google.com/github/YevheniiPotapenko/Files/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0__4_1_%D0%9F%D0%BE%D1%82%D0%B0%D0%BF%D0%B5%D0%BD%D0%BA%D0%B0_%D0%84%D0%B2%D0%B3%D0%B5%D0%BD%D0%B0_%D0%9E%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80%D0%BE%D0%B2%D0%B8%D1%87%D0%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Лабораторна робота 4_1, Потапенка Євгена Олександровича, Група ФІТ 2-15. Тема: «Робота з матрицями»

In [1]:
#Встaновити numpy
#!pip install numpy

In [2]:
# Приклади роботи з матрицями
import numpy as np
# Отримання версії бібліотеки NumPy
numpy_version = np.__version__
numpy_version


'2.0.2'

In [3]:
#1.
matrix = np.random.randint(1, 6, size =(3, 3))

matrix

array([[2, 5, 2],
       [1, 4, 1],
       [1, 2, 3]])

In [4]:
#2.
det = np.linalg.det(matrix)
det

np.float64(6.0)

In [5]:
#3.
product = np.prod(matrix)
product

np.int64(480)

In [6]:
#4.
sum = np.sum(matrix)
sum

np.int64(21)

In [7]:
#5.
max_element = np.max(matrix)
print("Найбільший елемент матриці ", max_element)
min_element = np.min(matrix)
print("Найменший елемент матриці ", min_element)

Найбільший елемент матриці  5
Найменший елемент матриці  1


In [8]:
# 6.
mean = np.mean(matrix)
mean

np.float64(2.3333333333333335)

In [9]:
#7
sqrt_matrix = np.sqrt(matrix)
sqrt_matrix

array([[1.41421356, 2.23606798, 1.41421356],
       [1.        , 2.        , 1.        ],
       [1.        , 1.41421356, 1.73205081]])

In [10]:
# 8
row_suns = np.sum(matrix, axis = 1).reshape(-1, 1)
row_suns

array([[9],
       [6],
       [6]])

In [11]:
# 9
vector = np.random.randint(0, 10, size = 25)
print("Початковий вектор:")
print(vector)
sorted_vector = np.sort(vector)[::-1]
print("Відсортований вектор:")
print(sorted_vector)

Початковий вектор:
[8 2 2 2 9 7 7 8 6 7 0 0 7 8 5 2 1 7 4 0 7 6 4 5 4]
Відсортований вектор:
[9 8 8 8 7 7 7 7 7 7 6 6 5 5 4 4 4 2 2 2 2 1 0 0 0]


In [12]:
#10
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)
print(mode)
print(median)
print(mean)
print(max_value)
print(min_value)

ModeResult(mode=np.int64(7), count=np.int64(6))
5.0
4.72
9
0


In [13]:
# 11
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

matrix_sum = matrix1 = matrix2
matrix_diff = matrix1 = matrix2
matrix_product = matrix1 = matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2!=0))
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)

Матриця 1:
[[ 2  9  8  2]
 [ 9  5  4  2]
 [ 5  2  7  9]
 [ 4 10 10  6]]

Матриця 2:
[[ 4  2  5  5]
 [ 9  7 10 10]
 [10  5  9 10]
 [ 9  5  9  2]]

Сума матриць:
[[ 4  2  5  5]
 [ 9  7 10 10]
 [10  5  9 10]
 [ 9  5  9  2]]

Різниця матриць:
[[ 4  2  5  5]
 [ 9  7 10 10]
 [10  5  9 10]
 [ 9  5  9  2]]

Поелементний добуток матриць:
[[ 4  2  5  5]
 [ 9  7 10 10]
 [10  5  9 10]
 [ 9  5  9  2]]


In [14]:
# 12
x = np.arange(9.0)
x


array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [15]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [16]:
x2 = np.arange(3.0)
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [17]:
#13.1
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [18]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [19]:
# 13.2
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1**x2

array([ 0,  1,  8, 27, 16,  5])

Висновок: Дана лабораторну роботу,ввела мене в курс діла стосовно свої  роботи із матрицями у коді, та зрозумів як вона працює.
